name: Check PR Title

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '^[-a-z]+: .+'
        allowed_prefixes: 'central-dashboard,katib,kserve,model-registry,notebooks,pipelines,spark-operator,trainer,gsoc,website,community'
        prefix_case_sensitive: false
        verbal_description: '{component}: {description}'
        github_token: ${{ secrets.GITHUB_TOKEN }}
